version: '3.8'

services:
  max-bot:
    build: .
    container_name: max-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  # Если планируется логирование в файл
    networks:
      - max-bot-network

networks:
  max-bot-network:
    driver: bridge